#!/usr/bin/env perl

# intelligent uncommenting, senses comment char from first line

$cmtc =  shift;

while (<STDIN>) {
  chomp;
  $cmtc = substr($_,0,1) unless $cmtc;
  s/^$cmtc+\s*//g;
  print "$_\n";
}
